[27기 양주영] 소셜 로그인
wecode-bootcamp-korea/27-2nd-workfolio-frontend pull request #1
Opened 2021-12-14 05:30 UTC by yangddu

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-14 08:34 UTC, younuk23 commented
주영님 아직 리뷰 진행할 정도로 정리가 안된 것 같습니다! 
사이더 코멘트 해결 및 목데이터 json 부분 포맷팅 맞춰주시고 구현 내용도 구두로 가이드 드린 부분 반영 안되있는것으로 보이는데 반영해서 수정해주세요!!

2021-12-17 01:18 UTC, younuk23 requested changes
주영님!
env ignore하는거랑 json 오류 고쳐주세요 다른 부분은 코멘트에 단 것 처럼 추후 반영해주시면 됩니다!!(꼭 하기)

json 파일 사용 안하는거면 삭제해주세요!

2021-12-17 01:18 UTC, yeonuk-hwang commented on public/data/detailMockData.json
> +}
이 json 파일에 문법적으로 오류가 있는 것 같네요 해결해주세요

2021-12-17 01:18 UTC, yeonuk-hwang commented on .env
> +REACT_APP_JAVASCRIPT_KEY=5bd276e03de90393f5e66e81bbfb2c52
- 이런 외부 API key들을 그대로 코드상에 노출하면 보안에 위협이 될 수 있습니다.
- 이런 코드상에 유출되면 안되는 정보들은 git으로 관리해서 github에 올라오게 되면 보안상에 위험합니다.
- gitignore에 `.env` 파일을 등록해서 github상에 노출되지 않도록 해주세요
- .gitignore에 등록하기 전에 한번이라도 git으로 관리해버린 파일들은(add, commit 등) 계속해서 git에 의해서 추적이 됩니다.
- 이를 없애기 위해서는 git의 기존 캐쉬를 삭제해줘야합니다.
- 아래의 명령어를 통해 캐쉬 삭제해주시고 git으로 추적 안되는 것 확인해주세요
- `git rm --cached 파일이름`

2021-12-17 01:18 UTC, younuk23 commented on src/pages/Login/Login.js
> +              alert('이미 로그인 되어 있습니다.');
access_token이 없는 경우, 즉 로그인이 실패한 경우가 이미 로그인되어있는 경우뿐만은 아닐 것 같아서 다양한 케이스에 대한 알맞는 에러처리를 고민해보시는게 좋을 것 같습니다!

이건 지금 처리하기에는 백엔드랑 맞춰야 할 게 좀 많을거라서 나중에 리팩토링 할 때 적용해보세요!

2021-12-17 01:18 UTC, younuk23 commented on src/pages/Login/Login.js
> +  background-color: ${props => props.theme.background};
```suggestion
  background-color: ${({theme}) => theme.background};
```

2021-12-17 01:18 UTC, younuk23 commented on src/pages/Login/Login.js
> +  align-items: center;
이런건 공용으로 많이 사용될 것 같아서 공통 mixin으로 분리하는것도 좋을 것 같네요 다음브랜치에서 팀원들이랑 상의해서 시도해보세요!!

2021-12-19 05:26 UTC, yangddu commented on public/data/detailMockData.json
> +}
넵! 확인하고 수정했습니다!

2021-12-19 05:29 UTC, yangddu commented on .env
> +REACT_APP_JAVASCRIPT_KEY=5bd276e03de90393f5e66e81bbfb2c52
넵! 캐쉬 삭제하고 추적 안되는 것 확인했습니다! 다음부턴 주의하겠습니다! 감사합니다

2021-12-19 05:29 UTC, yangddu commented on src/pages/Login/Login.js
> +              alert('이미 로그인 되어 있습니다.');
넵 확인했습니다! 감사합니다 😀

2021-12-19 05:29 UTC, yangddu commented on src/pages/Login/Login.js
> +  background-color: ${props => props.theme.background};
확인했고 수정했습니다 감사합니다!

2021-12-19 05:30 UTC, yangddu commented on src/pages/Login/Login.js
> +  align-items: center;
아하 넵!! 상의해보겠습니다 감사합니다 😀

2021-12-20 01:45 UTC, younuk23 approved these changes
LGTM 👍

2021-12-20 01:45 UTC, merged