[27기 김유량] nav bar layout 구현 중
wecode-bootcamp-korea/27-2nd-workfolio-frontend pull request #2
Opened 2021-12-14 09:35 UTC by YuryangKim

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- styled component를 최대한 활용하여 nav bar 구현 
- modal창 구현(날짜, 목적지)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. styled component로 layout 구현 중 입니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- styled component와 css 를 props로 받아서 스타일링 하는 법을 알게 되었습니다.

2021-12-16 09:23 UTC, younuk23 requested changes
고생하셨습니다 유량님 스타일드 컴포넌트 잘 공부해서 활용하셨네요 👍 
리뷰드린 사항 확인 및 반영해주세요!

2021-12-16 09:23 UTC, younuk23 commented on public/index.html
> +</html>
이부분은 굳이 수정할 필요가 없는 파트같네요!

2021-12-16 09:23 UTC, younuk23 commented on src/components/Nav/Nav.js
> +`;
이부분은 이 파일뿐만 아니라 전체 페이지 공통적으로 많이 쓰일 것 같아서 공용 mixin으로 분리하면 좋을 것 같네요!!
팀원들과 말해서 공용 mixin으로 분리해주세요!

2021-12-16 09:23 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  font-weight: ${props => props.theme.weightSemiBold};
```suggestion
  font-weight: ${({theme}) => theme.weightSemiBold};
```
함수 매개변수자리에서 구조분해할당해서 적용할 수 있습니다!

2021-12-16 09:23 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  display: block;
p tag 같은 경우 기본값이 display:block의 속성을 지니고 있습니다! 굳이 명시적으로 부여할 필요가 없는 속성입니다!

2021-12-16 10:38 UTC, YuryangKim commented on public/index.html
> +</html>
네 모달 공부하다가 index까지 추가하는 방법도 알아보다가 수정한듯 합니다

2021-12-16 11:11 UTC, YuryangKim commented on src/components/Nav/Nav.js
> +`;
넵 알겠습니다 !

2021-12-16 11:15 UTC, YuryangKim commented on src/components/Nav/Nav.js
> +  font-weight: ${props => props.theme.weightSemiBold};
오 몰랐던 사실인데 감사합니다 수정하겠습니다!

2021-12-16 11:16 UTC, YuryangKim commented on src/components/Nav/Nav.js
> +  display: block;
네 수정하겠습니당!

2021-12-17 01:27 UTC, younuk23 reviewed
유량님 리뷰 확인 및 반영해주세요

2021-12-17 01:27 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  flex: ${({ theme }) => theme.flex('row', 'center', 'space-between')};
```suggestion
  ${({ theme }) => theme.flex('row', 'center', 'space-between')};
```
이렇게 써야 적용될 것 같네요!! 확인해보고 수정해주세요!

2021-12-17 01:27 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  font-size: 16px;
16px은 기본값이라서 따로 기입 안해주셔도 됩니다!

2021-12-17 01:27 UTC, younuk23 commented on src/styles/theme.js
> +    `,
레퍼런스 찾아서 적용하신거면 반드시 어떻게 돌아가고 있는지 이해하는 과정도 반드시 진행해주세요!

2021-12-17 04:26 UTC, YuryangKim commented on src/components/Nav/Nav.js
> +  flex: ${({ theme }) => theme.flex('row', 'center', 'space-between')};
확인해봤더니 말씀해주신 대로 수정해야 적용이 되네요! 감사합니다

2021-12-17 04:26 UTC, YuryangKim commented on src/components/Nav/Nav.js
> +  font-size: 16px;
네 알겠습니당!

2021-12-17 04:27 UTC, YuryangKim commented on src/styles/theme.js
> +    `,
네 로직 이해해서 진행했습니당!

2021-12-20 01:45 UTC, younuk23 commented
컨플릭트 해결해주세요!

2021-12-20 05:30 UTC, YuryangKim commented
충돌 해결했습니다!

2021-12-20 06:40 UTC, younuk23 approved these changes
LGTM 👍

2021-12-20 06:41 UTC, merged