[27기 강인웅]목데이터 추가, 레이아웃 구현 ( 필터링 기능 구현 중)
wecode-bootcamp-korea/27-2nd-workfolio-frontend pull request #3
Opened 2021-12-14 12:38 UTC by wong0220

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 필터링 기능
- 지도 API 위치 기능

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 워크 스페이스 예약을 위한 여러가지 필터링 사항들 구현 중

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-15 06:04 UTC, younuk23 requested changes
고생하셨습니다 인웅님!
캘린더 라이브러리 잘 찾아보시고 문서 확인해서 잘 적용하신 것 같네요 👍 
리뷰사항 확인 및 반영해주세요!

2021-12-15 06:04 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/Filter.js
> +  };
3개중 하나만 open되고 나머지는 닫기는 로직 같은데 그러면 이렇게 3개의 state로 분리해서 각각 관리하는 것 보다 **현재 오픈된 것이 무엇이다** 를 관리하시는 state 하나를 만들어두고 사용하는식으로 하면 관리하는 로직도 편해질 것 같네요!

2021-12-15 06:04 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/Filter.js
> +  border-top: ${props => props.top};
```suggestion
  border-top: ${{top} => top};
```
함수 컴포넌트 사용할때와 마찬가지로 매개변수자리에서 구조분해 할당해서 사용할수도 있습니다! 참고하시고 적용해보세요!

2021-12-15 06:04 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/Filter.js
> +            right="5px"
고정적으로 사용되는 값들도 몇개 있는것 같은데 다들 props로 받고 있어서 다소 많은 것을 받고있다라는 생각이 드네요
기본적으로 자주 사용되는 값이 있으면 그 값을 기본값으로 설정해두고 따로 값을 props로 부여받는 경우에만 props로 받은 값을 사용하는식으로 활용해도 괜찮아보입니다! 시도해보세요!

2021-12-15 06:04 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/Filter.js
> +            background="#f2f2f2"
이렇게 자주 사용되는 색상들 같은 경우에는 theme에 넣어두고 사용하는 식이 추후 유지보수에 좋습니다! 팀원들이랑 상의해서 theme 추가해보세요!

2021-12-15 06:04 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/Filter.js
> +  margin-left: ${props => props.margin};
margin-left만 담당하는데 margin이라는 props이름은 다소 어색해보이네요!

2021-12-15 06:04 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/Filter.js
> +  margin-right: ${props => props.right};
```suggestion
  ${({margin, right}) => css`
      margin-left: ${margin};
      margin-right: ${right};
  `};
```
이런식으로도 표현 가능합니다! 참고해보세요

2021-12-15 06:04 UTC, younuk23 commented on src/pages/ListPage/Filter/Theme/Theme.js
> +      <input type="checkbox" id={el.theme} />
- HTML에서  `id` 는 문서 내에서 유일해야 합니다. 이러한 이유로 단일 요소를 다루는 경우 `id`를 사용할 수 있습니다.
- 하지만 정말로 해당 요소에 대한 이벤트나 스타일 핸들링이 프로젝트 전체에서 단 한번만 사용 되는지 충분히 고민해야합니다. 일반적으로 컴포넌트는 재사용 될 수 있기 때문에 같은 요소가 여러번 생성될 수 있습니다.
이러한 이유로 리액트 컴포넌트에서 id 사용은 권장되지 않습니다.

- label의 htmlFor을 위해서 어쩔수 없이 id를 사용하신 것 같은데 아래의 코드와 같이 <label> 안에 <input> 을 중첩시킬 경우 연관이 암시적이므로 for 및 id속성이 필요없어 불필요한 속성 사용을 줄일 수 있습니다. 아래 코드 예시를 확인해주세요.

```jsx
// 수정 전
<label htmlFor="connect-type">
    <input type="checkbox" name="connect" id="connect-type" />
</label>

// 수정 후
<label>
    <input type="checkbox" name="connect" />
</label>
```

2021-12-15 06:04 UTC, younuk23 commented on src/pages/ListPage/Filter/Theme/Theme.js
> +function Theme({ el }) {
el이라는 props이름보다는 의미가 명확히 드러나는 네이밍을 해주세요!

2021-12-15 06:04 UTC, younuk23 commented on src/pages/ListPage/Filter/Theme/Theme.js
> +const Lable = styled.label`
다른 스타일드 컴포넌트 선언부끼리는 공백 부여해주세요

2021-12-15 06:04 UTC, younuk23 commented on src/pages/ListPage/SpaceList/Building/Building.js
> +function Building({ space }) {
```suggestion
function Building({ space }) {
   const {title, city, ~~~~} = space;
}
```
구조분해할당 한번 더해서 쓰면 깔끔하겠네요!

2021-12-15 06:04 UTC, younuk23 commented on src/pages/ListPage/SpaceList/SpaceList.js
> +const Div = styled.div`
Div 등의 단순한 태그이름보다는 의미가 드러나는 이름을 지어주시는게 좋습니다!! 광범위하게 쓰이는 경우에는 어쩔 수 없지만 가능한 구체적인 의미가 드러나는 이름을 지어주세요!

2021-12-15 08:15 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +  border-top: ${props => props.top};
<img width="1440" alt="스크린샷 2021-12-15 오후 5 13 39" src="https://user-images.githubusercontent.com/73282508/146148745-e6a33d3c-b396-4921-a207-5675492ab260.png">

연욱님 이런식으로 수정했을 때 계속 오류가 나는데 제가 잘 못한 게 있을까요?

2021-12-15 12:10 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +  };
> 하나의 state로 관리하도록 수정하였고 함수의 경우도 하나로 줄였습니다!

2021-12-15 12:11 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +            right="5px"
고정적으로 사용하는 값들은 기본 값으로 설정해 두었고 유동적인 값들만 props로 받도록 수정하였습니다!

2021-12-15 12:12 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +            background="#f2f2f2"
네 알겠습니다!

2021-12-15 12:12 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +  margin-left: ${props => props.margin};
left로 수정완료 했습니다!

2021-12-15 12:13 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +  margin-right: ${props => props.right};
문법이 이해가 되지 않아서 반영을 못 시켰습니다 ㅠ

2021-12-15 12:14 UTC, wong0220 commented on src/pages/ListPage/Filter/Theme/Theme.js
> +      <input type="checkbox" id={el.theme} />
label안에 input 중첩 시켰고 리액트 컴포넌트 안에서의 id 사용은 지양하도록 하겠습니다!

2021-12-15 12:14 UTC, wong0220 commented on src/pages/ListPage/Filter/Theme/Theme.js
> +function Theme({ el }) {
el에서 themes로 네이밍 수정 완료 했습니다

2021-12-15 12:14 UTC, wong0220 commented on src/pages/ListPage/Filter/Theme/Theme.js
> +const Lable = styled.label`
공백 부여 완료했습니다

2021-12-15 12:15 UTC, wong0220 commented on src/pages/ListPage/SpaceList/Building/Building.js
> +function Building({ space }) {
구조 분해 할당 후 적용시켜줬습니다!

2021-12-15 12:16 UTC, wong0220 commented on src/pages/ListPage/SpaceList/SpaceList.js
> +const Div = styled.div`
약간의 의미가 드러나게 수정 완료했습니다!

2021-12-16 02:08 UTC, younuk23 commented on src/pages/ListPage/Filter/Filter.js
> +  border-top: ${props => props.top};
suggestion에서 제가 문법 오류 낸게 있었네요!!
`${({top}) => top};`
이런식으로 작성해주시면 됩니다!

2021-12-16 02:10 UTC, younuk23 commented on src/pages/ListPage/Filter/Filter.js
> +  margin-right: ${props => props.right};
지금은 매번 margin-left, margin-right마다 ${} 해서 props를 받아오는 과정을 거치는데 
props를 애초에 한번에 밭아와서 리턴값으로
```
      margin-left: ${margin};
      margin-right: ${right};
```
이런 문자열을 내보내는 방식입니다!
이해 안되시면 오늘 라운지에서 질문주세요!

2021-12-16 02:22 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!
페이지네이션은 잘 구현해주셨습니다 👍

2021-12-16 02:22 UTC, younuk23 commented on src/pages/ListPage/ListButton/ListButton.js
> +function ListButton({ el, clickPage }) {
여기도 el말고 의미가 드러나는 이름으로 수정해주세요!! 동일한 부분 있는지 확인 후 수정해주세요~!

2021-12-16 02:22 UTC, younuk23 commented on src/pages/ListPage/ListPage.js
> +        }
spaceList 부분은 잘 처리하셨는데 setPage를 for문을 돌면서 여러번 setState를 하는 것 같네요!!
setPage에 인자로 넣을 값을 만드는 과정을 위에서 다 처리하고, setPage는 한번만 하는 방식으로 수정해보세요!

2021-12-16 02:22 UTC, younuk23 commented on src/pages/ListPage/ListPage.js
> +        let number = Math.ceil(res.RESULT.count / 10);
number값 같은 경우 재할당 되지 않으니까 const로 선언해주는게 좋겠네요

2021-12-16 02:22 UTC, younuk23 commented on src/pages/ListPage/ListPage.js
> +            {page.map(el => (
앞으로 내 개발 인생에 el은 없다고 생각하고 의미가 있는 이름으로 수정해주세요~!

2021-12-16 02:22 UTC, younuk23 commented on src/pages/ListPage/SpaceList/SpaceList.js
> +const Ul = styled.div`
이름은 Ul인데 사실은 div ?! 다른 사람을 속이지 말아주세요... ㅋㅋㅋ

2021-12-16 02:22 UTC, younuk23 commented on src/pages/ListPage/ListPage.js
> +    setSortName(e.target.id);
로직에서 id를 사용하는 것은 지양해주세요! 다른 값으로 특정할 수 있도록 수정해주세요!!
Li를 map 돌리는 부분에서 상수데이터를 활용하면 원활하게 할 수 있어 보이네요!
HINT:
```js
const FILTER_LIST = [
  {
    filter:"headcount-high",
    title:"인원↑" 
  },
    {
    filter:"headcount-low",
    title:"인원↓"
  },
]
```

2021-12-16 12:30 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +  border-top: ${props => props.top};
> suggestion에서 제가 문법 오류 낸게 있었네요!! `${({top}) => top};` 이런식으로 작성해주시면 됩니다!

작성했습니다.

2021-12-16 12:33 UTC, wong0220 commented on src/pages/ListPage/Filter/Filter.js
> +  margin-right: ${props => props.right};
> 지금은 매번 margin-left, margin-right마다 ${} 해서 props를 받아오는 과정을 거치는데 props를 애초에 한번에 밭아와서 리턴값으로
> 
> ```
>       margin-left: ${margin};
>       margin-right: ${right};
> ```
> 
> 이런 문자열을 내보내는 방식입니다! 이해 안되시면 오늘 라운지에서 질문주세요!

시도해봤는데 오류가 나서 내일 여쭤보겠습니다!

2021-12-16 12:34 UTC, wong0220 commented on src/pages/ListPage/ListButton/ListButton.js
> +function ListButton({ el, clickPage }) {
수정완료했습니다!

2021-12-16 12:34 UTC, wong0220 commented on src/pages/ListPage/ListPage.js
> +        }
임시 변수 만들어서  한번만 렌더링 되도록 수정 완료 했습니다

2021-12-16 12:35 UTC, wong0220 commented on src/pages/ListPage/ListPage.js
> +        let number = Math.ceil(res.RESULT.count / 10);
수정완료했습니다!

2021-12-16 12:35 UTC, wong0220 commented on src/pages/ListPage/ListPage.js
> +            {page.map(el => (
네 앞으로 el은 죽어도 사용하지 않겠습니다

2021-12-16 12:35 UTC, wong0220 commented on src/pages/ListPage/SpaceList/SpaceList.js
> +const Ul = styled.div`
죄송합니다 ㅋㅋㅋㅋ 수정완료했습니다

2021-12-16 12:37 UTC, wong0220 commented on src/pages/ListPage/ListPage.js
> +    setSortName(e.target.id);
id에서 name 으로수정했고 상수데이터를 활용해서 수정했습니다!!

2021-12-17 02:19 UTC, younuk23 requested changes
고생하셨습니다 인웅님! 제가 생각하기에는 제가 가이드 드린 필터 쿼리스트링 이용한 방식으로 변환하는것은 다음 브랜치에서 작업하시는게 좋아보이네요!(지금 브랜치에서 이어서 하시면 작업량이 너무 방대해져서 리뷰가 계속 늘어나고 머지가 계속 늦어질 것 같네요!)

여기서 목표하신 작업 어느정도 마무리 됬으면 일단 1차적으로 이 브랜치는 머지하는게 좋을 것 같습니다! 하고 계신 추가구현 어느정도 마무리하시고 오늘 머지하시죠!

2021-12-17 02:19 UTC, yeonuk-hwang commented on src/pages/ListPage/Filter/CountryModal/CountryModal.js
> +          <MenuClose onClick={OpenModal}>           x         </MenuClose>   
빈칸보다는 마진으로 처리하는게 좋아보이네요!

2021-12-17 08:20 UTC, wong0220 commented
> 고생하셨습니다 인웅님! 제가 생각하기에는 제가 가이드 드린 필터 쿼리스트링 이용한 방식으로 변환하는것은 다음 브랜치에서 작업하시는게 좋아보이네요!(지금 브랜치에서 이어서 하시면 작업량이 너무 방대해져서 리뷰가 계속 늘어나고 머지가 계속 늦어질 것 같네요!)
> 
> 여기서 목표하신 작업 어느정도 마무리 됬으면 일단 1차적으로 이 브랜치는 머지하는게 좋을 것 같습니다! 하고 계신 추가구현 어느정도 마무리하시고 오늘 머지하시죠!

연욱님 제가 늦게 확인을 해서 이미 쿼리스트링 작업 중이였는데 지금까지 작업한 거 푸쉬하는 게 좋을까요 아니면 이어서 작업하는 게 좋을까요

2021-12-17 14:17 UTC, wong0220 commented on src/pages/ListPage/Filter/CountryModal/CountryModal.js
> +          <MenuClose onClick={OpenModal}>           x         </MenuClose>   
수정 완료했습니다!

2021-12-17 15:50 UTC, ghost commented on src/pages/ListPage/Filter/Filter.js
> +const Price = styled.span`
__[ESLint]__ 'styled' is not defined. ([view](https://sider.review/gh/repos/437749357/pulls/3#issue-6403865))

<details>

| Rule | Severity | Category | Recommended |
| ---- | -------- | -------- | ----------- |
| `no-undef` | `error` | Variables | Yes |

References:
- <https://eslint.org/docs/rules/no-undef>

You can [close this issue](https://sider.review/gh/repos/437749357/pulls/3#issue-6403865) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2021-12-17 15:50 UTC, ghost commented on src/pages/ListPage/Filter/Filter.js
> +const PriceRange = styled.div`
__[ESLint]__ 'styled' is not defined. ([view](https://sider.review/gh/repos/437749357/pulls/3#issue-6403866))

<details>

| Rule | Severity | Category | Recommended |
| ---- | -------- | -------- | ----------- |
| `no-undef` | `error` | Variables | Yes |

References:
- <https://eslint.org/docs/rules/no-undef>

You can [close this issue](https://sider.review/gh/repos/437749357/pulls/3#issue-6403866) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2021-12-20 01:47 UTC, younuk23 commented
연욱님 제가 늦게 확인을 해서 이미 쿼리스트링 작업 중이였는데 지금까지 작업한 거 푸쉬하는 게 좋을까요 아니면 이어서 작업하는 게 좋을까요
=> 작업하신것 올려주세요!

2021-12-20 04:31 UTC, wong0220 commented
> 연욱님 제가 늦게 확인을 해서 이미 쿼리스트링 작업 중이였는데 지금까지 작업한 거 푸쉬하는 게 좋을까요 아니면 이어서 작업하는 게 좋을까요 => 작업하신것 올려주세요!

네 작업한 거 올렸습니다 근데 사이더 오류사항에 관련해서 질문하고 싶은 부분이 있습니다!

2021-12-20 05:44 UTC, wong0220 commented
> 연욱님 제가 늦게 확인을 해서 이미 쿼리스트링 작업 중이였는데 지금까지 작업한 거 푸쉬하는 게 좋을까요 아니면 이어서 작업하는 게 좋을까요
> => 작업하신것 올려주세요!

기타 질문 및 특이 사항에 올렸습니다!

2021-12-20 06:49 UTC, younuk23 commented
제가 생각한 쿼리스트링으로 관리하는 로직은

1.필터링의 모든 값은 allList라는 state에서 관리

필터값 입력 후 검색버튼 혹은 적용버튼을 눌러서 allList state를 변경 시킴

allList state를 쿼리로 만들어준 후 navigate 해주는 로직을 allList를 타겟으로 잡은 useEffect 훅으로 감싸줌

navigate가 되면 useloaction 훅을 이용해 api 엔드포인트 끝에 loacation.search를 붙여 백엔드와 통신하여 데이터를 받음

이렇게 4가지 순서로 생각을 했는데 이렇게 짜고보니 문제점이 생겼었습니다.

    문제점

                1. 가장 중요한 url창에 쿼리를 가진 주소를 쳐서 접속하면 해당 필터에 맞게 렌더링이 됐다가 필터링이 풀린 원상태가 됨

    원인
                1. 렌더링 시  useEffect 감싸진  allList를 쿼리 식으로 만들어 주는 로직이 실행되고 navigate가 실행이 되버려서 아무 필터값도 갖.   지 않은  기본 조건으로 다시 렌더링이 되는 것이였음

    해결  
                1.가장 처음 페이지 렌더링 시 location search값을 allList 객체 형태로 만들어준 후에 스프레드 연산자로 allList에 셋 시켜주는 것

  위의 해결방법으로 문제점은 해결하였으나 동시에 다른 문제가 또 생겼습니다.
//////////////// -그로 인한 문제점
1. 처음 렌더링 시 딱 한 번만 실행하면 되기때문에 useEffect로 감싸주었고 타겟은 빈 배열로 주었더니 타겟을 잡아주라고 eslint 오류가 나옴

		2.근본적인 쿼리 스트링 관리법이 이게 맞는 것인지 의문
		
=> 
인웅님 쿼리스트링으로 전환 잘 시도해주신 것 같습니다! 다만 위의 질문주신 사항과 코드상에서 제가 가이드 드릴 부분이 동일해보여서 여기에 정리해서 답변드릴게요 답변내용 참고하셔서 코드 수정해주세요!!

지금 진행하시고 계시는 방법은 필터링을 queryString과 allList state를 모두 다 관리하고 있습니다.
그런데 우리는 queryString을 useLocation이라는 hook을 통해서 가져오고 이값이 state처럼 다뤄지고 있습니다(
react-router-dom에서 제공해주는 customHook입니다)
state를 사용하는 근본적인 이유를 보자면 state가 변할 때 화면을 re-render 해주기 위함입니다!
그런데 위리는 이미 queryString을 useLocation hook을 통해서 사용하고 있기에 queryString이 변경되면 다시 화면이 re-render 됩니다!
그래서 굳이 allList state와 queryString의 변화를 모두 신경쓰고 관리할 필요가 없습니다!
오히려 이렇게 진행하고 있기에 allList와 queryString의 sync를 맞춰줘야해서 로직이 복잡해지고 인웅님이 지금 고민하고 계신 여러 문제점이 생기게 됩니다

결론적으로 allList state를 없애고, useLocation으로 가져오는 queryString만으로 필터링 조건을 관리하는 식으로 진행해보세요!
필터링 조건이 변화됬을때는 queryString을 변화시키는 식으로 동작해주시면 됩니다!
위 사항 이해가 잘 안되시면 오늘은 제가 라운지에 없어서 라운지에 계시는 다른 프론트 멘토분들께 위의 질문 및 답변내용 보여드리고 이해안되는 부분 설명드리면 답변 잘 얻으실 수 있을겁니다!
조금만 더 하면 완성되겠네요 화이팅 💪

2021-12-21 14:02 UTC, wong0220 commented
> 제가 생각한 쿼리스트링으로 관리하는 로직은
> 
> 1.필터링의 모든 값은 allList라는 state에서 관리
> 
> 필터값 입력 후 검색버튼 혹은 적용버튼을 눌러서 allList state를 변경 시킴
> 
> allList state를 쿼리로 만들어준 후 navigate 해주는 로직을 allList를 타겟으로 잡은 useEffect 훅으로 감싸줌
> 
> navigate가 되면 useloaction 훅을 이용해 api 엔드포인트 끝에 loacation.search를 붙여 백엔드와 통신하여 데이터를 받음
> 
> 이렇게 4가지 순서로 생각을 했는데 이렇게 짜고보니 문제점이 생겼었습니다.
> 
> ```
> 문제점
> 
>             1. 가장 중요한 url창에 쿼리를 가진 주소를 쳐서 접속하면 해당 필터에 맞게 렌더링이 됐다가 필터링이 풀린 원상태가 됨
> 
> 원인
>             1. 렌더링 시  useEffect 감싸진  allList를 쿼리 식으로 만들어 주는 로직이 실행되고 navigate가 실행이 되버려서 아무 필터값도 갖.   지 않은  기본 조건으로 다시 렌더링이 되는 것이였음
> 
> 해결  
>             1.가장 처음 페이지 렌더링 시 location search값을 allList 객체 형태로 만들어준 후에 스프레드 연산자로 allList에 셋 시켜주는 것
> ```
> 
> 위의 해결방법으로 문제점은 해결하였으나 동시에 다른 문제가 또 생겼습니다. //////////////// -그로 인한 문제점
> 
> 1. 처음 렌더링 시 딱 한 번만 실행하면 되기때문에 useEffect로 감싸주었고 타겟은 빈 배열로 주었더니 타겟을 잡아주라고 eslint 오류가 나옴
>    ```
>     2.근본적인 쿼리 스트링 관리법이 이게 맞는 것인지 의문
>    ```
> 
> => 인웅님 쿼리스트링으로 전환 잘 시도해주신 것 같습니다! 다만 위의 질문주신 사항과 코드상에서 제가 가이드 드릴 부분이 동일해보여서 여기에 정리해서 답변드릴게요 답변내용 참고하셔서 코드 수정해주세요!!
> 
> 지금 진행하시고 계시는 방법은 필터링을 queryString과 allList state를 모두 다 관리하고 있습니다. 그런데 우리는 queryString을 useLocation이라는 hook을 통해서 가져오고 이값이 state처럼 다뤄지고 있습니다( react-router-dom에서 제공해주는 customHook입니다) state를 사용하는 근본적인 이유를 보자면 state가 변할 때 화면을 re-render 해주기 위함입니다! 그런데 위리는 이미 queryString을 useLocation hook을 통해서 사용하고 있기에 queryString이 변경되면 다시 화면이 re-render 됩니다! 그래서 굳이 allList state와 queryString의 변화를 모두 신경쓰고 관리할 필요가 없습니다! 오히려 이렇게 진행하고 있기에 allList와 queryString의 sync를 맞춰줘야해서 로직이 복잡해지고 인웅님이 지금 고민하고 계신 여러 문제점이 생기게 됩니다
> 
> 결론적으로 allList state를 없애고, useLocation으로 가져오는 queryString만으로 필터링 조건을 관리하는 식으로 진행해보세요! 필터링 조건이 변화됬을때는 queryString을 변화시키는 식으로 동작해주시면 됩니다! 위 사항 이해가 잘 안되시면 오늘은 제가 라운지에 없어서 라운지에 계시는 다른 프론트 멘토분들께 위의 질문 및 답변내용 보여드리고 이해안되는 부분 설명드리면 답변 잘 얻으실 수 있을겁니다! 조금만 더 하면 완성되겠네요 화이팅 💪

연욱님이 주신 리뷰 토대로 리팩토링 했습니다! 기타 질문사항에 궁금한 점 또한 작성했습니다

2021-12-22 08:01 UTC, younuk23 commented
컨플릭 해결해주세요~!

2021-12-22 08:33 UTC, wong0220 commented
> 컨플릭 해결해주세요~!

컨플릭트 해결 완료했습니다

2021-12-22 09:24 UTC, younuk23 approved these changes

2021-12-22 09:24 UTC, merged