[27기] Main Slider library를 사용하여 레이아웃 구현 중
wecode-bootcamp-korea/27-2nd-workfolio-frontend pull request #6
Opened 2021-12-19 18:01 UTC by YuryangKim

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- slick library를 이용하여 slide 기능 구현
- map을 통해 이미지 및 정보 추출 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- map을 통해 이미지를 뽑아와서 레이아웃을 구현하는 중입니다. 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- map function, slick library에 대한 기능 구현을 더 알게 되었습니다. 

<br />

## 질문 사항
map을 해서 이미지를 뽑아오는데 콘솔에서는 이미지가 들어오는 게 보이는데
slick의 <img> 태그 안에서는 보이지 않습니다. 
어떤 부분이 잘못 되었는지 잘 모르겠습니다.

2021-12-20 01:55 UTC, younuk23 commented
conflict 나는 부분이 많아서 해결하고 나서 다시 리뷰 보겠습니다! 컨플릭 해결해서 다시 push 해주세요!
***
map을 해서 이미지를 뽑아오는데 콘솔에서는 이미지가 들어오는 게 보이는데
slick의  태그 안에서는 보이지 않습니다.
어떤 부분이 잘못 되었는지 잘 모르겠습니다.
***
=> 어떤 부분이 잘못됬는지 모르겠다는 과정에서 끝나고 바로 질문으로 이어지는 게 아니라, 잘못된 부분이 어디인지 추측해보고 실제 그부분을 수정도 해보고, 검색해서 실제 문서에서 설명한 내용과 내가 사용한 부분이 어떤 차이점을 가지고 있는지 분석하고 판단하는 과정을 반드시 거쳐주셔야 합니다. 그렇지 않고 그냥 바로바로 질문으로 해결하는 식으로 습관을 들이면 나중에 실제 주위의 도움없이 개발을 진행해야 할 때 벽에 부딪힙니다! 
유량님의 실력증진을 위해서 좀 더 능동적인 태도로 임해주세요!!

2021-12-20 05:30 UTC, YuryangKim commented
네 ㅠㅠ

2021-12-23 07:39 UTC, younuk23 requested changes
유량님 env gitignore 처리해주세요! + conflict 해결해주세요!

2021-12-23 07:39 UTC, younuk23 commented on .env
> +REACT_APP_JAVASCRIPT_KEY=5bd276e03de90393f5e66e81bbfb2c52
- 이런 외부 API key들을 그대로 코드상에 노출하면 보안에 위협이 될 수 있습니다.
- gitignore에 `.env` 파일을 등록해서 github상에 노출되지 않도록 해주세요
- .gitignore에 등록하기 전에 한번이라도 git으로 관리해버린 파일들은(add, commit 등) 계속해서 git에 의해서 추적이 됩니다.
- 이를 없애기 위해서는 git의 기존 캐쉬를 삭제해줘야합니다.
- 아래의 명령어를 통해 캐쉬 삭제해주시고 git으로 추적 안되는 것 확인해주세요
- `git rm --cached 파일이름`

2021-12-23 08:07 UTC, YuryangKim commented on .env
> +REACT_APP_JAVASCRIPT_KEY=5bd276e03de90393f5e66e81bbfb2c52
네 알겠습니다!

2021-12-23 08:51 UTC, merged